<#
build_years.ps1 - season manifest + (optional) season bundler for the Year toggle.

Two jobs:

1) MANIFEST (always): regenerate data/years.js from what's on disk.
   - The baseline season ships flat (data/plays.js) and is loaded synchronously.
   - Every data/<year>/ folder that contains plays.js is a self-registering bundle
     (regData(...) calls) that the app injects on demand.
   - `preferred` is set to the latest season present, so the dashboard opens on the
     current year once it exists (the user can still click back).

2) BUNDLE (when -Bundle <Year> -StageDir <path> is given): take the freshly built
   FLAT files in <StageDir>/data (window.X={...}) and rewrite them into data/<Year>/
   as regData(<Year>,'X',{...}) so loading them never clobbers another season's
   globals. Copies the per-team plays/ folder and plays_index.json alongside.
   The 2025 baseline in data/ is never touched.

Usage:
  ./build_years.ps1                                   # just regen the manifest
  ./build_years.ps1 -Bundle 2026 -StageDir ./stage    # wrap staged 2026 build, then regen
#>
param(
  [string]$Root       = "C:/Users/miles/saints-dashboard",
  [int]   $DefaultYear = 2025,
  [int]   $Bundle     = 0,
  [string]$StageDir   = ""
)
$ErrorActionPreference = "Stop"
$dataDir = Join-Path $Root "data"

# ---- BUNDLE: wrap staged flat files into data/<Year>/ as regData ----
if($Bundle -gt 0){
  if(-not $StageDir){ throw "-Bundle requires -StageDir" }
  $srcData = Join-Path $StageDir "data"
  if(-not (Test-Path $srcData)){ throw "No staged data at $srcData" }
  $destDir = Join-Path $dataDir "$Bundle"
  New-Item -ItemType Directory -Force -Path $destDir | Out-Null

  # per-team play files + index (copied verbatim; fetched by path, not eval'd)
  $srcPlays = Join-Path $srcData "plays"
  if(Test-Path $srcPlays){
    $destPlays = Join-Path $destDir "plays"
    New-Item -ItemType Directory -Force -Path $destPlays | Out-Null
    Copy-Item (Join-Path $srcPlays "*.json") $destPlays -Force
  }
  $srcIdx = Join-Path $srcData "plays_index.json"
  if(Test-Path $srcIdx){ Copy-Item $srcIdx (Join-Path $destDir "plays_index.json") -Force }

  # every generated *.js except the schedule (an upcoming-season singleton, kept flat)
  $skip = @("sched.js","years.js")
  Get-ChildItem (Join-Path $srcData "*.js") | Where-Object { $skip -notcontains $_.Name } | ForEach-Object {
    $txt = [System.IO.File]::ReadAllText($_.FullName)
    $eq  = $txt.IndexOf('=')
    if($eq -lt 0){ return }
    $lhs  = $txt.Substring(0,$eq).Trim()
    $name = $lhs -replace '^window\.',''
    $body = $txt.Substring($eq+1).TrimEnd()
    if($body.EndsWith(';')){ $body = $body.Substring(0,$body.Length-1).TrimEnd() }
    $wrapped = "regData($Bundle,`"$name`",$body);`n"
    $outFile = Join-Path $destDir $_.Name
    [System.IO.File]::WriteAllText($outFile,$wrapped,[System.Text.UTF8Encoding]::new($false))
  }
  Write-Output "bundled $Bundle -> $destDir"
}

# ---- MANIFEST: scan disk, emit data/years.js ----
# baseline (flat)
$seasons = @([ordered]@{ y=$DefaultYear; label="$DefaultYear"; baseline=$true; pbase="data/plays/" })
$maxYear = $DefaultYear

# namespaced bundles: any data/<year>/plays.js
Get-ChildItem $dataDir -Directory | Where-Object { $_.Name -match '^\d{4}$' } | ForEach-Object {
  $y = [int]$_.Name
  if($y -eq $DefaultYear){ return }               # baseline is already the flat set
  if(-not (Test-Path (Join-Path $_.FullName "plays.js"))){ return }
  $src = @(Get-ChildItem (Join-Path $_.FullName "*.js") | Sort-Object Name | ForEach-Object { "data/$y/$($_.Name)" })
  $seasons += [ordered]@{ y=$y; label="$y"; pbase="data/$y/plays/"; src=$src }
  if($y -gt $maxYear){ $maxYear = $y }
}

$seasons = $seasons | Sort-Object { $_.y }
function JStr($s){ '"' + ($s -replace '\\','\\' -replace '"','\"') + '"' }
$sJs = ($seasons | ForEach-Object {
  $parts = @("y:$($_.y)","label:$(JStr $_.label)","pbase:$(JStr $_.pbase)")
  if($_.baseline){ $parts += "baseline:true" }
  if($_.Contains('src')){ $parts += "src:[" + (($_.src | ForEach-Object { JStr $_ }) -join ",") + "]" }
  "  { " + ($parts -join ", ") + " }"
}) -join ",`n"

$js = "/* Generated by build_years.ps1 - do not edit by hand. */`n" +
      "window.YEARS = {`n" +
      "  default: $DefaultYear,`n" +
      "  preferred: $maxYear,`n" +
      "  seasons: [`n$sJs`n  ]`n};`n"
[System.IO.File]::WriteAllText((Join-Path $dataDir "years.js"),$js,[System.Text.UTF8Encoding]::new($false))
Write-Output "years.js -> default $DefaultYear, preferred $maxYear, seasons: $(($seasons | ForEach-Object { $_.y }) -join ', ')"
